services:
  crawler:
    pull_policy: build
    build: .
    ports:
      - "3456:3456"
    env_file:
      - stack.env
    restart: on-failure
    security_opt: 
      - seccomp=/home/crawler/engine/chrome.json
